[package]
name = "peer_peer_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.3.5"
tokio = { version = "1.32.0", features = ["full"] }
local-ip-address = "0.5.4"
